# Numerical calculus with NumPy

In [2]:
import numpy as np # usually imported with this abbreviation

print(np.__version__)

1.26.2


In [3]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

We can specify the data type of values in the array. Also, we can use some basic array filled with initial values (zeros, ones, other), or use other basic intialization (arange, linspace, random)

In [4]:
v1 = np.zeros(10, dtype=int)
m2 = np.ones ((3, 5), dtype = float)
M = np.full ((4, 4), 3.14)

print(v1)
print(m2)
print(M)

v1 = np.arange(0, 20, 2) # similar to Python range
v2 = np.linspace(0, 1, 5) # equi-spaced vector (start, end, increment)
print(v1)
print(v2)

M = np.eye(3) # identity matrix
print(M)

vr = np.random.randn(10) # sample from the standard normal distribution (10 is the size of the array)
print(vr)

[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[-0.73231719  0.74983086  1.82519161 -0.58059063  0.18395112  0.15854686
  0.72885254  0.06422319 -0.7673617  -0.90843827]


Check the type of an array

# Dimensions in Arrays

In [5]:
arr = np.array(42)
print("0-D array:", arr)

arr = np.array([1, 2, 3, 4, 5])
print("1-D array:", arr)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("2-D array:", arr)

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("3-D array:", arr)

0-D array: 42
1-D array: [1 2 3 4 5]
2-D array: [[1 2 3]
 [4 5 6]]
3-D array: [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


**Check Number of Dimensions**

In [6]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


**Dim vs shape vs size**

**Shape**: a tuple composed with the size of each axis (or dimension) of the array

In [7]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(5,)
(2, 3)
(4, 2, 3)


**Size**: The overall size (or number of values) contained in the array. We can compute the size as the product of the size of each dimension 

In [8]:
print(a.size)
print(b.size) # 5x1
print(c.size) # 2x3
print(d.size) # 2x2x3

1
5
6
24


**Copy an array**

In [9]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy() # it is like deepcopy() in python (create a new array)

print(arr)
print(x)

Y = arr.view() # it is like copy in python
arr[0] = 42

print("Original array:", arr)
print(Y)

Z = arr
Z[2] = 24
print("Original array:", arr)
print(Z)

[1 2 3 4 5]
[1 2 3 4 5]
Original array: [42  2  3  4  5]
[42  2  3  4  5]
Original array: [42  2 24  4  5]
[42  2 24  4  5]


# Slicing and Indezing Arrays

In [10]:
# INDEXING Examples

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])
print('45th element on 1st row: ', arr[0, -1])

arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2]) # each index refers to a dimension!

2nd element on 1st row:  2
5th element on 2nd row:  10
45th element on 1st row:  5
6


Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [11]:
# SLICING Examples

np.random.seed(0) # seed for reproducibility
x2 = np.random.randint(10, size=(3, 4)) # 2-dimensional array

print(f"x2\n{x2}")
print(f"slice: x2[:2, :3]\n{x2[:2, :3]}") # 2 rows, 3 columns

x2_2 = x2[:,::2] # all rows, every other column
print(f"slice: x2[:, ::2]\n{x2_2}")
print(f"reversed: x2[::-1, ::-1]\n{x2[::-1,::-1]}")
print(f"first row: {x2[0]}") # same as x2[0,:]
print(f"first column: {x2[:,0]}")
print("modifying x2_2[0,0]")

x2_2[0,0] = -15
print(f"x2_2[0,0]: {x2_2[0,0]}, x2[0,0]: {x2[0,0]}")

x2_2_copy = x2[:,::2].copy() # all rows, every other column
print("now modifying x2_2_copy[0,0]")

x2_2_copy[0,0] = 21
print(f"x2_2_copy[0,0]: {x2_2_copy[0,0]}, x2[0,0]: {x2[0,0]}")

x2
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
slice: x2[:2, :3]
[[5 0 3]
 [7 9 3]]
slice: x2[:, ::2]
[[5 3]
 [7 3]
 [2 7]]
reversed: x2[::-1, ::-1]
[[6 7 4 2]
 [5 3 9 7]
 [3 3 0 5]]
first row: [5 0 3 3]
first column: [5 7 2]
modifying x2_2[0,0]
x2_2[0,0]: -15, x2[0,0]: -15
now modifying x2_2_copy[0,0]
x2_2_copy[0,0]: 21, x2[0,0]: -15


# Reshape

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# reshape from 1D to 2D
newarr = arr.reshape(4, 3)
print(newarr)

# reshape from 2D to 3D
newarr = arr.reshape(2, 3, 2)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**Can We Reshape Into any Shape?**

Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

ValueError: cannot reshape array of size 8 into shape (3,3)

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("Original shape:", arr.shape)

newarr = arr.reshape(2, 2, -1)

print("new arr 1:", newarr)
print("New shape 1:", newarr.shape)

newarr = arr.reshape(2, 4, -1)

print("new arr 2:", newarr)
print("New shape 2:", newarr.shape)

# squeeze() function cancel 1d extra dimensions of an array
newarr = newarr.squeeze()
print("new arr 2:", newarr)
print("New shape 2:", newarr.shape)

Original shape: (8,)
new arr 1: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
New shape 1: (2, 2, 2)
new arr 2: [[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]]
New shape 2: (2, 4, 1)
new arr 2: [[1 2 3 4]
 [5 6 7 8]]
New shape 2: (2, 4)


**Flattening** array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original shape:", arr.shape)
newarr = arr.reshape(-1)

print(newarr)
print("New shape:", newarr.shape)

Original shape: (2, 3)
[1 2 3 4 5 6]
New shape: (6,)


# Array iteration

If we iterate on a 1-D array it will go through each element one by one.

In a 2-D array it will go through all the rows.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


Iterate on each scalar element of the 2-D array:



In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In a 3-D array it will go through all the 2-D arrays.



In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

for x in arr:
  for y in x:
    for z in y:
      print(z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


# Join Array

Joining means putting contents of two or more arrays in a single array.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])


arr = np.concatenate((arr1, arr2), axis=0)
print("Concatenate along the first axis:\n", arr)

arr = np.concatenate((arr1, arr2), axis=1)
print("Concatenate along the second axis: \n", arr)

Concatenate along the first axis:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate along the second axis: 
 [[1 2 5 6]
 [3 4 7 8]]


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
print(arr1.shape)

arr = np.stack((arr1, arr2), axis=0) 
print(arr)

arr = np.stack((arr1, arr2), axis=1) 
print(arr)

(3,)
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


# Sort Array

In [ ]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[0 1 2 3]
[[2 3 4]
 [0 1 5]]


# Random

NumPy offers the random module to work with random numbers.



In [ ]:
from numpy import random

x = random.randint(100)

print(x)

88


The random module's rand() method returns a random float between 0 and 1.


In [ ]:
x = random.rand()

print(x)

x = random.rand(3, 5) # we can specify the shape

print(x)

0.23274412927905685
[[0.61446471 0.03307459 0.01560606 0.42879572 0.06807407]
 [0.25194099 0.22116092 0.25319119 0.13105523 0.01203622]
 [0.1154843  0.61848026 0.97425621 0.990345   0.4090541 ]]


In [ ]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(20))

print(x)

x = random.choice([3, 5, 7, 9], p=[0.1, 0.1, 0.6, 0.2], size=(3, 5))

print(x)

[7 7 5 5 3 5 5 7 7 7 5 5 5 7 3 7 7 7 5 5]
[[7 7 7 5 7]
 [3 7 3 7 7]
 [7 9 7 3 7]]


**Normal Distribution**

The Normal Distribution is one of the most important distributions.

It is also called the Gaussian Distribution.
Use the random.normal() method to get a Normal Data Distribution.

It has three parameters:

loc - (Mean) where the peak of the bell exists.

scale - (Standard Deviation) how flat the graph distribution should be.

size - The shape of the returned array.

In [ ]:
x = random.normal(size=(2, 3))
print(x)

[[ 3.10153058  0.85875415 -1.15477553]
 [ 0.94183434 -0.28213514 -0.97565467]]


In [ ]:
x = random.normal(loc=1, scale=2, size=(2, 3))
print(x)

[[ 2.65914219  0.58536401  3.23599721]
 [ 3.12849937  3.30265967 -0.54491541]]


# Matrix operations

**Matrix Transposition**

In [18]:
x = np.random.rand(2, 4) # we can specify the shape
print(x)
print(x.shape)

x_t = x.T
print(x_t)
print(x_t.shape)

[[0.67887953 0.72063265 0.58201979 0.53737323]
 [0.75861562 0.10590761 0.47360042 0.18633234]]
(2, 4)
[[0.67887953 0.75861562]
 [0.72063265 0.10590761]
 [0.58201979 0.47360042]
 [0.53737323 0.18633234]]
(4, 2)


**Matrix multiplication**: The @ perform a matrix multiplication, so the order of the operands it is relevant. I reported here an example of multiplying 

In [30]:
A = x_t @ x
print("x_t @ x:\n", A)
print(A.shape)
print("\n")
B = x @ x_t
print("x @ x_t:\n", B)
print(B.shape)

x_t @ x:
 [[1.03637508 0.56956592 0.754402   0.50616631]
 [0.56956592 0.53052784 0.46958036 0.40698271]
 [0.754402   0.46958036 0.5630444  0.40100893]
 [0.50616631 0.40698271 0.40100893 0.32348973]]
(4, 4)


x @ x_t:
 [[1.60770587 0.96710393]
 [0.96710393 0.84573119]]
(2, 2)


**Inverse of a matrix**

In [29]:
from numpy.linalg import inv # this operator is used to compute the inverse of a matrix

square_mat = np.array([[1,2],[3,4]]) # create a 2x2 matrix
print("Squared matrix:\n", square_mat)

print("Inverted Squared matrix:\n",inv(square_mat)) # compute the inverse of the matrix

print("Identity proof:\n", square_mat @ inv(square_mat)) # compute the product of the matrix and its inverse (should be the identity matrix)

Squared matrix:
 [[1 2]
 [3 4]]
Inverted Squared matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Identity proof:
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
